# Generated by Django 5.1 on 2024-10-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_file_document_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='authorship_percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='publication_date',
            field=models.DateField(default='2024-04-02'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
