# Generated by Django 5.1 on 2024-10-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_authorship_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='authorship_percentage',
            field=models.IntegerField(default=100),
        ),
    ]
