# Generated by Django 5.1 on 2024-10-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_author_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='academic_fields',
            field=models.ManyToManyField(blank=True, to='core.academicfield'),
        ),
    ]
