# Generated by Django 5.1 on 2024-10-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document_academic_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='filename',
        ),
    ]
