# Generated by Django 5.1 on 2024-10-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_test_type_test_user_analysisjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_selector',
            field=models.CharField(choices=[('ml', 'ML'), ('unigram', 'Unigram'), ('bigram', 'Bigram'), ('trigram', 'Trigram')], default='ml', max_length=30),
            preserve_default=False,
        ),
    ]
