# Generated by Django 5.1 on 2024-10-21 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_word_word_selector'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='language',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.CASCADE, to='core.language'),
            preserve_default=False,
        ),
    ]
