# Generated by Django 5.1 on 2024-10-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_paragraph_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageproficiency',
            name='proficiency',
            field=models.CharField(choices=[('A1', 'A1 (Beginner)'), ('A2', 'A2 (Elementary)'), ('B1', 'B1 (Intermediate)'), ('B2', 'B2 (Upper Intermediate)'), ('C1', 'C1 (Advanced)'), ('C2', 'C2 (Proficient)'), ('native', 'Native')], max_length=6),
        ),
    ]
