# Generated by Django 5.1 on 2024-10-23 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_languageproficiency_proficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='document',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.document'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_selector',
            field=models.CharField(choices=[('ml', 'ML'), ('unigram', 'Unigram'), ('bigram', 'Bigram'), ('trigram', 'Trigram'), ('most_used_content_word', 'most_used_content_word'), ('least_used_content_word', 'least_used_content_word'), ('random', 'random')], max_length=30),
        ),
    ]
