# Generated by Django 5.1 on 2024-10-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_test_document_alter_word_word_selector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='success_estimate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
