# Generated by Django 5.1 on 2024-10-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_test_success_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='show_preview',
            field=models.BooleanField(default=False),
        ),
    ]
