# Generated by Django 5.1 on 2024-10-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_test_show_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='type',
            field=models.CharField(choices=[('authorML', 'Author'), ('previewML', 'Reviewer'), ('randomML', 'Tester'), ('try', 'Try')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(choices=[('high_school', 'High School Graduation or Lower'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('doctorate', 'Doctorate Degree or Higher')], max_length=20, verbose_name='Education'),
        ),
    ]
