# Generated by Django 5.1.6 on 2025-10-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_test_type_alter_user_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_export_data',
            field=models.BooleanField(default=False),
        ),
    ]
