# Generated by Django 6.0.5 on 2026-05-12 12:51

from django.db import migrations, models


def backfill_nulls(apps, schema_editor):
    Language = apps.get_model("core", "Language")
    Document = apps.get_model("core", "Document")
    User = apps.get_model("core", "User")
    Language.objects.filter(name__isnull=True).update(name="")
    Document.objects.filter(author__isnull=True).update(author="")
    Document.objects.filter(released_at__isnull=True).update(released_at="")
    User.objects.filter(gender__isnull=True).update(gender="")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_can_export_data'),
    ]

    operations = [
        migrations.RunPython(backfill_nulls, reverse_code=migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='released_at',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1, verbose_name='Gender (optional)'),
        ),
    ]
