# Generated by Django 6.0.5 on 2026-05-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_drop_semicorrect_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='selection_method',
            field=models.CharField(blank=True, choices=[('ml_noun_unigram', 'Unigram nouns (ML)'), ('ml_adj_unigram', 'Unigram adjectives (ML)'), ('adj_adv_bigram', 'Adjectives + adverbs'), ('noun_adj_bigram', 'Nouns + adjectives'), ('noun_adj_adv_trigram', 'Nouns + adjectives + adverbs'), ('trigram_with_adj', 'Trigrams containing adjectives')], max_length=30, null=True),
        ),
    ]
