# Generated by Django 6.0.5 on 2026-05-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_word_selection_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='selection_method',
            field=models.CharField(blank=True, choices=[('ml_noun_unigram', 'Unigram nouns (ML)'), ('ml_adj_unigram', 'Unigram adjectives (ML)'), ('bigram', 'Bigram (any)'), ('adj_adv_trigram', 'Trigrams w/ adjectives + adverbs'), ('noun_adj_adv_trigram', 'Trigrams w/ nouns + adjectives + adverbs'), ('noun_adj_trigram', 'Trigrams w/ nouns + adjectives'), ('trigram_with_adj', 'Trigrams containing adjectives')], max_length=30, null=True),
        ),
    ]
