# Generated by Django 6.0.5 on 2026-05-29 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_legacy_bigram_selection_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveSmallIntegerField(blank=True, help_text='Which retry attempt failed (1-based). Null for run-wide failures.', null=True)),
                ('kind', models.CharField(choices=[('network_error', 'Network error'), ('http_status', 'HTTP non-200 status'), ('non_json', 'Non-JSON response body'), ('unhandled', 'Unhandled exception')], max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_logs', to='core.analysisjob')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='tests_analy_created_44c500_idx')],
            },
        ),
    ]
