# Generated by Django 6.0.5 on 2026-09-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_word_source_shape'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analysisfailurelog',
            new_name='core_analys_created_9f3b7d_idx',
            old_name='tests_analy_created_44c500_idx',
        ),
    ]
